### ISSUE TITLE
No cstring.h ?

### ISSUE THREAD

**Issue by roberttco** [Uberi/Arduino-CommandParser#1]
Hello - I am trying to use your command parser library but I don't have cstring.h on my computer (i.e. it doesn't seem to be part of my stock Arduino IDE install.)  Is it missing from your library ?

**Comment by pblase** [comment]
Same problem. It was present for the Due board but not for the Nano.

**Comment by pblase** [comment]
Error message:

Arduino: 1.8.12 (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from C:\Users\pblase\Documents\Arduino\Command_Parser_Test\Command_Parser_Test.ino:1:0:

C:\Users\pblase\Documents\Arduino\libraries\CommandParser\src/CommandParser.h:16:10: fatal error: cstring: No such file or directory

 #include <cstring>

          ^~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Arduino Nano.

**Comment by pblase** [comment]
It appears as if the "cstring.h" library is present for ARM processors but not for AVR processors.

**Comment by Uberi** [comment]
Hey @roberttco and @pblase,

Thanks for the bug report! I've just released v1.1.0, which should bring full support for AVR processors - avr-libc was missing cstring, unfortunately. v1.1.0 will be live tomorrow in your Arduino Library manager, or you can grab it from this repo right now!

Please feel free to reopen if anything else comes up.
